### ISSUE TITLE
Return a page not found  when the user brute forced into non existing question.

### ISSUE THREAD

**Issue by PeanutPK** [TAGCH/ku-polls#53]
Return page not found when the user brute forced to proceed to the non-existing question URL.

<img width="566" alt="image" src="https://github.com/user-attachments/assets/34394a32-be4d-41d2-847a-d3240695f386">
<img width="566" alt="image" src="https://github.com/user-attachments/assets/31b6eda7-0028-4ef0-9716-963ddd848532">

**Comment by TAGCH** [comment]
I've already fixed it. I've added the get_object() method to the DetailView and ResultView classes to handle the nonexistent question (e.g., http://127.0.0.1:8000/polls/9999/ and http://127.0.0.1:8000/polls/9999/results). Now, when you go to path 'http://127.0.0.1:8000/polls/9999/' or 'http://127.0.0.1:8000/polls/9999/results', it will redirect you to the index page with the error message popping up on the screen.
