### ISSUE TITLE
x on the left side

### ISSUE THREAD

**Issue by PeanutPK** [TAGCH/ku-polls#54]
Somehow there is an x on the left side of the screen it is not doing anything except moving the questions up by a little bit.

<img width="312" alt="image" src="https://github.com/user-attachments/assets/cb779235-9a90-44f8-bab6-d69965b5be56">

**Comment by TAGCH** [comment]
I think the CSS does not load because of 'DEBUG = False'. I will update the 'installation.md' to correct the install process. Apologize for the mistake.

![index](https://github.com/user-attachments/assets/8273353b-e26a-4f48-ac12-ff3d4b8992e2)
