### ISSUE TITLE
Wrong hyperlink in README.md

### ISSUE THREAD

**Issue by Pichayanon** [TAGCH/ku-polls#69]
In REAMDE.md line 5,  It should link to Django Documentation : [Writing your first Django app](https://docs.djangoproject.com/en/4.1/intro/tutorial01/) , not to the doc : [Django Todo Tutorial](https://docs.google.com/document/d/1wfOcNPAhNnZ702mKd32uoSazEhja2lIAFSjxV3va5wU/edit#heading=h.ei2uwhrew9rm).

**Comment by TAGCH** [comment]
Finish
